#!/usr/bin/env bash
#
# install.sh — first-time setup for the Apache reverse-proxy InvenTree deployment.
#
# Prompts for the domain and admin credentials, writes .env, then pulls the
# images, runs the initial database setup and starts the stack. TLS / Apache is
# NOT configured by this script — see the README for the manual vhost + certbot
# steps (the example vhost lives in apache/).

set -euo pipefail

cd "$(dirname "$0")"

# --- helpers ---------------------------------------------------------------

err()  { printf '\033[31m%s\033[0m\n' "$*" >&2; }
info() { printf '\033[36m%s\033[0m\n' "$*"; }
ok()   { printf '\033[32m%s\033[0m\n' "$*"; }

# Resolve the docker compose command (plugin vs legacy binary).
if docker compose version >/dev/null 2>&1; then
    DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
    DC="docker-compose"
else
    err "Docker Compose not found. Install Docker Engine + the compose plugin first."
    exit 1
fi

command -v docker >/dev/null 2>&1 || { err "docker not found."; exit 1; }

# --- guard against clobbering an existing install ---------------------------

if [ -f .env ]; then
    err "A .env file already exists — refusing to overwrite it."
    err "This looks like an existing install. Use ./update.sh instead, or remove .env manually."
    exit 1
fi

# --- collect configuration -------------------------------------------------

info "InvenTree (Apache reverse-proxy) installer"
echo

read -rp "Public domain (e.g. inventree.example.org): " DOMAIN
[ -n "$DOMAIN" ] || { err "Domain is required."; exit 1; }

read -rp "Admin username [admin]: " ADMIN_USER
ADMIN_USER="${ADMIN_USER:-admin}"

read -rp "Admin email: " ADMIN_EMAIL
[ -n "$ADMIN_EMAIL" ] || { err "Admin email is required."; exit 1; }

while :; do
    read -rsp "Admin password: " ADMIN_PASSWORD; echo
    [ -n "$ADMIN_PASSWORD" ] || { err "Password cannot be empty."; continue; }
    read -rsp "Confirm admin password: " ADMIN_PASSWORD2; echo
    [ "$ADMIN_PASSWORD" = "$ADMIN_PASSWORD2" ] && break
    err "Passwords do not match — try again."
done

# Database password: random by default (it is internal to the docker network).
DB_PASSWORD="$(openssl rand -hex 24)"
ok "Generated a random PostgreSQL password (stored in .env)."

# --- write .env ------------------------------------------------------------

info "Writing .env ..."
cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# See .env.template for documentation of every option.

COMPOSE_PROJECT_NAME=inventree
INVENTREE_TAG=stable

INVENTREE_SITE_URL="https://${DOMAIN}"
INVENTREE_WEB_PORT=8000

INVENTREE_USE_X_FORWARDED_HOST=True
INVENTREE_USE_X_FORWARDED_PORT=True
INVENTREE_USE_X_FORWARDED_PROTO=True

INVENTREE_EXT_VOLUME=./inventree-data
INVENTREE_LOG_LEVEL=WARNING
INVENTREE_PLUGINS_ENABLED=True
INVENTREE_AUTO_UPDATE=True

INVENTREE_ADMIN_USER=${ADMIN_USER}
INVENTREE_ADMIN_PASSWORD=${ADMIN_PASSWORD}
INVENTREE_ADMIN_EMAIL=${ADMIN_EMAIL}

INVENTREE_DB_ENGINE=postgresql
INVENTREE_DB_NAME=inventree
INVENTREE_DB_HOST=inventree-db
INVENTREE_DB_PORT=5432
INVENTREE_DB_USER=pguser
INVENTREE_DB_PASSWORD=${DB_PASSWORD}

INVENTREE_CACHE_ENABLED=True
INVENTREE_CACHE_HOST=inventree-cache
INVENTREE_CACHE_PORT=6379

INVENTREE_GUNICORN_TIMEOUT=90
EOF
chmod 600 .env

mkdir -p inventree-data

# --- bring up the stack ----------------------------------------------------

info "Pulling images ..."
$DC pull

info "Running initial database setup (invoke update) ..."
$DC run --rm inventree-server invoke update

info "Starting containers ..."
$DC up -d

ok ""
ok "InvenTree is running and listening on http://127.0.0.1:8087 (loopback only)."
cat <<EOF

Next steps — configure Apache + TLS (NOT done automatically):

  1. Copy the example vhost and edit the ServerName for ${DOMAIN}:
       sudo cp apache/inventree.darkcosmos.org.conf \\
               /etc/apache2/sites-available/${DOMAIN}.conf
       sudo \$EDITOR /etc/apache2/sites-available/${DOMAIN}.conf

  2. Enable the required modules:
       sudo a2enmod proxy proxy_http proxy_wstunnel headers ssl rewrite

  3. Obtain a certificate (use certonly so certbot leaves the vhost alone):
       sudo certbot certonly --apache -d ${DOMAIN}

  4. Enable the site and reload:
       sudo a2ensite ${DOMAIN}
       sudo apache2ctl configtest && sudo systemctl reload apache2

Then browse to https://${DOMAIN} and log in as '${ADMIN_USER}'.
EOF
